name: Build Extension

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux build dependencies (32-bit/64-bit)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-12 g++-12 gcc-multilib g++-multilib \
            libstdc++6 lib32stdc++6 \
            libc6-dev libc6-dev-i386 \
            linux-libc-dev linux-libc-dev:i386 \
            lib32z1-dev zlib1g-dev:i386

      - name: Checking out SourceMod
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/sourcemod
          ref: 1.12-dev
          path: sourcemod-1.12
          submodules: recursive

      - name: Checking out MM:Source
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/metamod-source
          ref: 1.12-dev
          path: metamod-1.12

      - name: Checking out AMBuild
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/ambuild
          path: ambuild 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setting up ambuild
        working-directory: ambuild
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python setup.py install

      # - name: Checking out hl2sdk-tf2
      #   uses: actions/checkout@v6
      #   with:
      #     repository: alliedmodders/hl2sdk
      #     ref: tf2
      #     path: hl2sdk-tf2

      - name: Configure and Build
        run: |
          mkdir -p build && cd build
          python ../configure.py --enable-optimize --sm-path="${{ github.workspace }}/sourcemod-1.12" --mms-path="${{ github.workspace }}/metamod-1.12"
          ambuild

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: sm-extension-package
          path: build/package/