name: Build Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install Linux build dependencies (32-bit/64-bit)
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Checking out SourceMod
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/sourcemod
          ref: 1.12-dev
          path: sourcemod-1.12
          submodules: recursive

      - name: Copy asm
        run: |
          cp -r ${{ github.workspace }}/asm ${{ github.workspace }}/sourcemod-1.12/public/asm

      - name: Copy libudis86
        run: |
          cp -r ${{ github.workspace }}/libudis86 ${{ github.workspace }}/sourcemod-1.12/public/libudis86

      - name: Checking out MM:Source
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/metamod-source
          ref: 1.12-dev
          path: metamod-1.12
          submodules: recursive

      - name: Checking out AMBuild
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/ambuild
          path: ambuild 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setting up ambuild
        working-directory: ambuild
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python setup.py install

      - name: Checking out hl2sdk-manifests
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/hl2sdk-manifests
          ref: master
          path: hl2sdk-manifests

      - name: Checking out hl2sdk-tf2
        uses: actions/checkout@v6
        with:
          repository: alliedmodders/hl2sdk
          ref: tf2
          path: hl2sdk-tf2

      # - name: Checking out hl2sdk-sdk2013
      #   uses: actions/checkout@v6
      #   with:
      #     repository: alliedmodders/hl2sdk
      #     ref: sdk2013
      #     path: hl2sdk-sdk2013

      - name: Configure and Build
        run: |
          mkdir -p build && cd build
          python ../configure.py --enable-optimize --sm-path="${{ github.workspace }}/sourcemod-1.12" --mms-path="${{ github.workspace }}/metamod-1.12" --hl2sdk-manifest-path="${{ github.workspace }}/hl2sdk-manifests" --sdks="tf2" --targets="x86,x86_64"
          ambuild

      - name: Upload extension package
        uses: actions/upload-artifact@v4
        with:
          name: sm-extension-package
          path: build/package/